import Image from 'next/image';
import styles from '../../styles/general.module.scss';
export default function Page() {
    return (
    <>
        STIMMING --> AUTOESTIMULACIÓN
        REPETICIÓN DE MOVIMIENTOS FISICOS O DE OBJETOS
        AUTISTAS, TDAH,
        
        ES UNA RESPUESTA A LA HIPERSENSIBILIDAD YA QUE
        ASÍ SE BLOQUEAN LOS ESTIMULOS EXTERNOS
        
        EJEMPLOS
        COLOR WHILE TALKING
        SINGING WHILE DOING THINGS
        SHAKING YOUR LEG WHILE READING
        CHASQUEAR LOS DEDOS
        BATERIA CON OBJETOS
        CALCULAR CON LOS DEDOS
        
        ESTO MUCHAS VECES NOS PUEDE LLEVAR A LA
        AUTOLESIÓN
        HERIDAS EN LOS DEDOS, (SKIN PICKING)
        RASGARSE, ARAÑARSE, APRETAR LOS PUÑOS PARA HACERSE DAÑO CON LAS UÑAS
        (DESORDENES ALIMENTICIOS Y ABUSO SUSTANCIAS NO ENTRAN AQUI)
        SU PROPOSITO NO ES EL SUICIDIO
        APARECE EN MUCHOS TRASTORNOS COMO T LIMITE PERSONALIDAD
        DEPRESION, ANSIEDAD, ESTRES, ESQUIZOFRENIA
        
        ALIVIA SENSACIONES INTENSAS (ESTRATEGIA DE AFRONTAMIENTO)
        PASA EN OTROS ANIMALES COMO AVES Y MONOS</p><p>siempre te han dicho que hablas mucho?


    </>
    )
}